#!/bin/bash

POKEMON="pikachu"
URL="https://pokeapi.co/api/v2/pokemon/$POKEMON"
OUTPUT="data.json"
ERROR_LOG="errors.txt"

curl -s -f "$URL" -o "$OUTPUT"

if [ $? -ne 0 ]; then
    echo "[$(date)] Failed to fetch data for $POKEMON from $URL" >> "$ERROR_LOG"
    exit 1
else
    echo "[$(date)] Successfully fetched data for $POKEMON"
fi
